version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: node_db_dev
    environment:
      MYSQL_ROOT_PASSWORD: Admin123
      MYSQL_DATABASE: node_assessment
      MYSQL_USER: node_assessment
      MYSQL_PASSWORD: Admin123
    ports:
      - "3306:3306"
    volumes:
      - db_data_dev:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: node_app_dev
    environment:
      - DATABASE_URL=mysql://node_assessment:Admin123@db:3306/node_assessment
      - DB_NAME=node_assessment
      - DB_USER=node_assessment
      - DB_PASSWORD=Admin123
      - DB_HOST=db
      - PORT=3000
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    command: sh -c "npx prisma migrate deploy && npm run dev"
    restart: unless-stopped

volumes:
  db_data_dev: